-- 0001  Create the unified `users` table (replaces reps + access_requests).
-- ADDITIVE: reps and access_requests are left in place; the cutover that drops
-- them happens in a later migration once the app reads from `users`.
--
-- Design notes:
--   * id is an internal, immutable surrogate (GENERATED BY DEFAULT AS IDENTITY)
--     so we can seed it to match existing reps.id values, keeping every existing
--     rep_id foreign-key value valid for the eventual FK repoint.
--   * email is the everyday human key: stored lowercased, with a case-insensitive
--     UNIQUE index (citext is not allow-listed on Azure, so we use lower(email)).
--   * role/status carry the access model; password_hash + must_change_password
--     carry credentials (formerly in access_requests).

CREATE TABLE IF NOT EXISTS users (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                text    NOT NULL,
  name                 text    NOT NULL,
  role                 text    NOT NULL DEFAULT 'rep'
                         CHECK (role IN ('rep','manager','admin','sysadmin')),
  password_hash        text,
  must_change_password boolean NOT NULL DEFAULT false,
  is_active            boolean NOT NULL DEFAULT true,
  status               text    NOT NULL DEFAULT 'Approved'
                         CHECK (status IN ('Pending','Approved','Rejected')),
  rep_code             text,
  initials             text,
  zone                 text,
  route                text,
  target_cr            numeric,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness on email (the everyday key).
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key ON users (lower(email));
CREATE INDEX IF NOT EXISTS idx_users_role   ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_active ON users(is_active);
