-- 0003  Flat many-to-many client ownership ("who has access to this client").
-- Replaces clients.primary_rep_id / secondary_rep_id (kept for now; dropped at
-- cutover). No primary/secondary distinction — all owners are equal.

CREATE TABLE IF NOT EXISTS client_assignments (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id   integer NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  user_id     integer NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  assigned_by integer REFERENCES users(id) ON DELETE SET NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (client_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_client_assignments_user   ON client_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_client_assignments_client ON client_assignments(client_id);

-- Backfill from existing primary rep (skip junk reps absent from `users`).
INSERT INTO client_assignments (client_id, user_id, assigned_at)
SELECT c.id, c.primary_rep_id, COALESCE(c.created_at, now())
FROM clients c
WHERE c.primary_rep_id IS NOT NULL
  AND EXISTS (SELECT 1 FROM users u WHERE u.id = c.primary_rep_id)
ON CONFLICT (client_id, user_id) DO NOTHING;

-- Backfill from existing secondary rep (currently 0 rows, future-proof).
INSERT INTO client_assignments (client_id, user_id, assigned_at)
SELECT c.id, c.secondary_rep_id, COALESCE(c.created_at, now())
FROM clients c
WHERE c.secondary_rep_id IS NOT NULL
  AND EXISTS (SELECT 1 FROM users u WHERE u.id = c.secondary_rep_id)
ON CONFLICT (client_id, user_id) DO NOTHING;
