-- 0005  Assignment audit trail (sysadmin-visible in the frontend).
-- Records every change to client ownership, client→tour, tour assignments,
-- and user records, with before/after snapshots.

CREATE TABLE IF NOT EXISTS assignment_audit (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,   -- 'client_owner' | 'client_tour' | 'tour_assignment' | 'user'
  entity_id   text NOT NULL,   -- client id, tour id/name, or user email
  action      text NOT NULL,   -- 'add' | 'remove' | 'update' | 'create' | 'delete'
  old_value   jsonb,
  new_value   jsonb,
  changed_by  text,            -- acting user's email (stored lowercased)
  changed_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_assignment_audit_entity     ON assignment_audit(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_assignment_audit_changed_at ON assignment_audit(changed_at DESC);
