-- Exhibition module — self-contained.
--
-- The module owns its records end to end. Its ONLY connection to existing portal
-- data is a LOOKUP: when a company is typed against a meeting we try to match it
-- to a row in `clients`, and if we match, we keep the id so the UI can flag it as
-- an existing client. Nothing here writes to clients, contacts, tasks or
-- opportunities, and no exhibition figure feeds a pipeline or revenue KPI.
-- company_name is always stored in full, so a meeting is complete on its own
-- whether or not the company is known to the CRM.
--
-- users(id) is referenced for people because that is the portal's single identity
-- table; there is no separate exhibition user master.

CREATE TABLE IF NOT EXISTS exhibitions (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text NOT NULL,
  organizer       text,
  website         text,
  venue           text,
  city            text,
  state           text,
  country         text DEFAULT 'India',
  industry        text,
  source          text,
  start_date      date,
  end_date        date,
  -- Lifecycle. Draft is where discovery lands; Submitted awaits a decision;
  -- Approved carries a participation type; Rejected is terminal but retained.
  status          text NOT NULL DEFAULT 'Draft'
                    CHECK (status IN ('Draft','Shortlisted','Submitted','Approved',
                                      'Rejected','Ongoing','Completed','Closed')),
  participation   text CHECK (participation IN ('Exhibit','Visit')),
  suggested       text CHECK (suggested IN ('Exhibit','Visit')),
  estimated_cost_inr numeric(14,2),
  recommendation  text,
  -- Whoever must decide. Named per exhibition rather than "any admin" — 14 of the
  -- 31 active users hold admin or above, so role alone is too broad a gate.
  approver_id     integer REFERENCES users(id) ON DELETE SET NULL,
  submitted_by    integer REFERENCES users(id) ON DELETE SET NULL,
  submitted_at    timestamptz,
  decided_by      integer REFERENCES users(id) ON DELETE SET NULL,
  decided_at      timestamptz,
  decision_notes  text,
  created_by      integer REFERENCES users(id) ON DELETE SET NULL,
  created_by_name text,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_at      timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT exhibitions_dates_ok
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS idx_exhibitions_status ON exhibitions (status);
CREATE INDEX IF NOT EXISTS idx_exhibitions_start  ON exhibitions (start_date DESC);

CREATE TABLE IF NOT EXISTS exhibition_team (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exhibition_id integer NOT NULL REFERENCES exhibitions(id) ON DELETE CASCADE,
  user_id       integer NOT NULL REFERENCES users(id)       ON DELETE CASCADE,
  team_role     text NOT NULL DEFAULT 'Member'
                  CHECK (team_role IN ('Team Lead','Member')),
  added_by      integer REFERENCES users(id) ON DELETE SET NULL,
  added_at      timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (exhibition_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_exhibition_team_user ON exhibition_team (user_id);

-- Append-only decision history, so the trail survives a re-submission after
-- "need more information" instead of being overwritten.
CREATE TABLE IF NOT EXISTS exhibition_approvals (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exhibition_id integer NOT NULL REFERENCES exhibitions(id) ON DELETE CASCADE,
  decision      text NOT NULL
                  CHECK (decision IN ('Submitted','Exhibit','Visit','Reject','More Info')),
  actor_id      integer REFERENCES users(id) ON DELETE SET NULL,
  actor_name    text,
  comments      text,
  created_at    timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_exhibition_approvals_exh
  ON exhibition_approvals (exhibition_id, created_at DESC);

-- Money going OUT. Rupees at numeric(14,2), deliberately not the crore columns the
-- pipeline uses: exhibition spend is lakhs-scale, exactly the range where a rupee
-- figure sitting in a crore column still looks plausible and quietly corrupts
-- totals. Nothing here is ever summed into a pipeline or revenue figure.
CREATE TABLE IF NOT EXISTS exhibition_expenses (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exhibition_id integer NOT NULL REFERENCES exhibitions(id) ON DELETE CASCADE,
  category      text NOT NULL,
  description   text,
  vendor        text,
  estimated_inr numeric(14,2),
  actual_inr    numeric(14,2),
  paid_inr      numeric(14,2) NOT NULL DEFAULT 0,
  paid_on       date,
  created_by    integer REFERENCES users(id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT NOW(),
  updated_at    timestamptz NOT NULL DEFAULT NOW(),
  -- Spec business rule: you cannot pay more than the bill.
  CONSTRAINT exhibition_expenses_paid_ok
    CHECK (actual_inr IS NULL OR paid_inr <= actual_inr)
);
CREATE INDEX IF NOT EXISTS idx_exhibition_expenses_exh ON exhibition_expenses (exhibition_id);

-- One invoice per expense line, stored inline like every other attachment in the
-- portal (opportunity_quotation_files / bug_screenshots / visit_photos).
CREATE TABLE IF NOT EXISTS exhibition_expense_files (
  expense_id  integer PRIMARY KEY REFERENCES exhibition_expenses(id) ON DELETE CASCADE,
  file_name   text NOT NULL,
  mime_type   text NOT NULL,
  bytes       bytea NOT NULL,
  uploaded_by integer REFERENCES users(id) ON DELETE SET NULL,
  uploaded_at timestamptz NOT NULL DEFAULT NOW()
);

-- A conversation at the stand.
--
-- client_id is the module's ONLY link to existing portal data and is purely the
-- result of a lookup: set when the typed company matched a clients row, NULL
-- otherwise. ON DELETE SET NULL so removing a client never destroys the meeting.
-- company_name is populated either way, so the module never depends on the CRM to
-- render its own history.
CREATE TABLE IF NOT EXISTS exhibition_meetings (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exhibition_id  integer NOT NULL REFERENCES exhibitions(id) ON DELETE CASCADE,
  client_id      integer REFERENCES clients(id) ON DELETE SET NULL,
  company_name   text NOT NULL,
  contact_person text,
  designation    text,
  phone          text,
  email          text,
  city           text,
  discussion     text,
  requirement    text,
  outcome        text,
  next_action    text,
  follow_up_date date,
  interest       text CHECK (interest IN ('Hot','Warm','Cold')),
  potential_value_inr numeric(14,2),
  met_by         integer REFERENCES users(id) ON DELETE SET NULL,
  met_by_name    text,
  met_on         date,
  created_at     timestamptz NOT NULL DEFAULT NOW(),
  updated_at     timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_exhibition_meetings_exh    ON exhibition_meetings (exhibition_id);
CREATE INDEX IF NOT EXISTS idx_exhibition_meetings_client ON exhibition_meetings (client_id);
CREATE INDEX IF NOT EXISTS idx_exhibition_meetings_follow ON exhibition_meetings (follow_up_date)
  WHERE follow_up_date IS NOT NULL;

COMMENT ON COLUMN exhibition_meetings.client_id IS
  'Lookup result only - the single connection between the Exhibition module and the CRM. NULL means the company is not a known client; the module never creates or edits clients.';
