-- Quotation attachments: one document per opportunity → many.
--
-- The 1:1 was enforced by nothing more than the primary key sitting on
-- opportunity_id, so the conversion is mostly a key swap: a surrogate id takes
-- over as the key and opportunity_id becomes an ordinary indexed FK. That is
-- the same shape as visit_photos and complaint_photos, which have always been
-- 1:N, so the routes and UI can follow their established pattern.
--
-- The 196 existing rows keep their bytes and are handed ids in upload order.
-- Nothing about opportunities.quotation_link changes: it keeps pointing at the
-- collection endpoint, which still streams the oldest (primary) document, so
-- every link already stored in the DB, already exported to Excel, and already
-- sent to a client still resolves to the same file.
--
-- uploaded_by / uploaded_by_name are added because with several documents on
-- one quote "who attached this one" becomes a real question. visit_photos and
-- complaint_photos both carry uploaded_by; the name is denormalised alongside
-- it so the list survives a user being deactivated, matching how
-- exhibitions.created_by_name is handled.

-- The old PK is the only thing forbidding a second row. Dropped by its real
-- generated name, guarded so a re-run is a no-op.
ALTER TABLE opportunity_quotation_files
  DROP CONSTRAINT IF EXISTS opportunity_quotation_files_pkey;

ALTER TABLE opportunity_quotation_files
  ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY;

-- Existing rows were assigned ids by the ADD COLUMN above; make it the key.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'opportunity_quotation_files'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE opportunity_quotation_files
      ADD CONSTRAINT opportunity_quotation_files_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- opportunity_id lost its unique index along with the PK, and every read is
-- "all documents for this opportunity", so it needs its own index back.
CREATE INDEX IF NOT EXISTS opportunity_quotation_files_opportunity_id_idx
  ON opportunity_quotation_files (opportunity_id, uploaded_at, id);

ALTER TABLE opportunity_quotation_files
  ADD COLUMN IF NOT EXISTS uploaded_by      integer REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS uploaded_by_name text;
