-- Business cards photographed at a meeting.
--
-- Many per meeting on purpose: a conversation at a stand usually involves two or
-- three people, and the back of a card often carries the detail worth keeping.
-- Same shape as visit_photos and complaint_photos — a surrogate key, the parent
-- as an indexed FK, and the bytes in their own table so a plain SELECT on
-- exhibition_meetings never drags an image along.
--
-- The card is the record. The meeting's own contact_person / designation /
-- phone / email fields stay the typed version, so a card that is blurred or in a
-- script nobody present reads still preserves what was handed over.

CREATE TABLE IF NOT EXISTS exhibition_meeting_cards (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id       integer NOT NULL REFERENCES exhibition_meetings(id) ON DELETE CASCADE,
  file_name        text NOT NULL,
  mime_type        text NOT NULL,
  byte_size        integer,
  bytes            bytea NOT NULL,
  uploaded_by      integer REFERENCES users(id) ON DELETE SET NULL,
  uploaded_by_name text,
  uploaded_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS exhibition_meeting_cards_meeting_id_idx
  ON exhibition_meeting_cards (meeting_id, uploaded_at, id);
