-- A bug report carries as many screenshots as the reporter wants to attach.
--
-- bug_screenshots was keyed on bug_id alone, so the second shot on a report had
-- nowhere to go: inserting it would have collided with the first. Everything
-- else about the table was already right — a child of bugs, bytes inline,
-- ON DELETE CASCADE, the same shape complaint_attachments has — so it gets its
-- own surrogate key rather than being replaced by a new table. The screenshots
-- already filed stay exactly where they are, bytes and all, and the id each one
-- picks up is what the new per-screenshot download route addresses them by.

ALTER TABLE bug_screenshots DROP CONSTRAINT IF EXISTS bug_screenshots_pkey;

-- Dropping the primary key leaves the implied NOT NULL behind, but say it out
-- loud: a screenshot with no bug is an orphan nothing would ever serve.
ALTER TABLE bug_screenshots ALTER COLUMN bug_id SET NOT NULL;

-- integer, not bigint, so `pg` hands the ids back to the page as JS numbers
-- rather than strings when they are aggregated into an array.
ALTER TABLE bug_screenshots
  ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY;

-- Guarded so a re-run does not try to add a second primary key.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'bug_screenshots'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE bug_screenshots ADD PRIMARY KEY (id);
  END IF;
END $$;

-- bug_id used to be the key and so was indexed for free; it is the lookup the
-- bug tracker makes on every card, so it needs an index of its own now.
CREATE INDEX IF NOT EXISTS idx_bug_screenshots_bug ON bug_screenshots (bug_id, id);

COMMENT ON TABLE bug_screenshots IS
  'Screenshots attached to a bug report — many per bug, shown oldest first by id.';
